### ISSUE TITLE
ONNX Edge WG meeting invite signup 

### ISSUE THREAD

**Issue by moljacq** [onnx/working-groups#1]
We are planning to have regular meetings for Edge WG.  
First meeting is currently planned for **Thu Apr 4, 2019 at 8:00 am PST** 
Info about each meeting will be posted to https://gitter.im/onnx/edge.

If you want to get meeting invite via email please comment with the following info:
- Name/Affiliation and desired email address for invites
- (Optional) Preferred week days and times for future meetings (will try to accommodate majority as much as possible)

**Comment by hannibalhuang** [comment]
Is it 8:00am or 8:00pm PT ?

**Comment by moljacq** [comment]
It is 8am. Just updated it. Thanks.

**Comment by tombaker1** [comment]
Thanks for organizing this.  Please add me.  
Thomas Baker
Intel
thomas.baker@intel.com
Tue, Thu, Fri

**Comment by ssgwos** [comment]
Saurabh Tangri
saurabhtangri@intel.com
Tue, Thu, Fri

**Comment by moljacq** [comment]
Could everybody interested in attending meetings after Apr 4 fill out [Find a time for ONNX Edge WG meetings](https://forms.gle/VSKc3uQEJgoSQLdw8) survey? Thanks.

**Comment by moljacq** [comment]
Info about first meeting **Thu Apr 4, 2019 at 8:00 am PST** has been posted to https://gitter.im/onnx/edge.

**Comment by moljacq** [comment]
@ssgwos, is your email above correct? Or is it saurabh.tangri@intel.com?
