### ISSUE TITLE
Issue about the attendance for the next Edge WG meeting

### ISSUE THREAD

**Issue by lyd911** [onnx/working-groups#5]
Hi, Edge WG members,
I am wondering whether or not we still hold our weekly meetings as planned since recent events might cause some troubles to some members. The regulation does not forbid activities conducted by open source community which is publicly available and transparent, so theoretically I can still attend the ONNX Edge WG meeting but I need confirm from ONNX since I do not want to cause troubles for any community members @prasanthpul , thanks.
I paused on my work on the proposal we scheduled to discuss in the next meeting, uploading to Github is halted for now, so we can change our agenda and talk about other topics first @moljacq , thanks

**Comment by moljacq** [comment]
Hi @lyd911, 
This is a valid question and concern, which needs to be addressed by onnx steering committee. We need guidance in this regard. + @jspisak.
As for the coming onnx edge wg meeting on May 29, not sure what other topic to cover, other then general discussion in context of the proposal, similar to what we have done last time. I will try to reach out to onnx steering committee tomorrow about the guidance and may be able to provide updates in the meeting.  
I will send updates about the meeting on the gitter channel. There is also possibility it could be canceled...

**Comment by lyd911** [comment]
Hi @moljacq ,
Thanks for your reply, since the schedule for next meeting is coming near and the SC also needs time to respond, a better and a safe way is to postpone my agenda and discuss other topics first. We will wait for the conclusion from the SC and hope there is a clear guidance. Thanks.

**Comment by jspisak** [comment]
Thanks for the patience guys. I am checking with my legal and will advise shortly.

**Comment by lyd911** [comment]
Hi, @jspisak 
Any update ?

**Comment by jspisak** [comment]
Yes, sorry, I thought @moljacq would have jumped in. From the SG perspective, this is fine to move forward.

**Comment by lyd911** [comment]
Thanks @jspisak, will resume my documentation works and looking forward to attend the weekly meeting next week
