### ISSUE TITLE
Final discussion on discussion_materials/ONNX Edge scope and profile definition.md

### ISSUE THREAD

**Issue by moljacq** [onnx/working-groups#7]
This issue is to be used for 2 purposes:
- final comments on the document
- acceptance vote
Current active contributors: @lyd911, @OferRosenberg, @ssgwos, @moljacq

**Comment by moljacq** [comment]
Link to the document: https://github.com/onnx/working-groups/blob/master/edge/discussion_materials/ONNX%20Edge%20scope%20and%20profile%20definition.md

**Comment by moljacq** [comment]
I will make some updates directly in the document, as commenting to some typos and slight wording changes seems as overkill to comment here.

**Comment by moljacq** [comment]
I would move Edge scenario radar chart just above https://github.com/onnx/working-groups/blob/master/edge/discussion_materials/ONNX%20Edge%20scope%20and%20profile%20definition.md#1-accuracy. Reason is that this is where we are introducing attributes, which sets the context for the chart .

**Comment by moljacq** [comment]
I just made updates to the document. Please take a look : https://github.com/onnx/working-groups/commit/0a78d1ed7eda02fa0712b0b238c02103b7f804a8#diff-5a9f20e897606cb780825b9766d9b172 
I moved radar chart as I already suggested. Pretty much all updates are rewording related in "Edge profile attributes" section.
Please take a look ASAP, and comment if something needs updates. 
I plan to send out request for vote tomorrow.

**Comment by moljacq** [comment]
Lets do acceptance vote for https://github.com/onnx/working-groups/blob/master/edge/discussion_materials/ONNX%20Edge%20scope%20and%20profile%20definition.md document.

Active Edge WG contributors ( @lyd911, @OferRosenberg, @ssgwos, @moljacq ), do you accept content of the document and agree to officially publish it into artifacts? 
Please reply with Yes or No by Jul 1 2019.
Thanks

**Comment by lyd911** [comment]
Yes

**Comment by OferRosenberg** [comment]
Yes

**Comment by moljacq** [comment]
Yes

**Comment by ssgwos** [comment]
yes

**Comment by moljacq** [comment]
Approved document https://github.com/onnx/working-groups/blob/master/edge/discussion_materials/ONNX%20Edge%20scope%20and%20profile%20definition.md and associated png files are copied to artifacts folder. File name format was changed to match style of SOW document. 
Now officially published..
